### Register new user
POST http://localhost:8080/api/register
content-type:application/json

{
    "username": "user@example.com",
    "password": "mypass"
}

### Login new user
POST http://localhost:8080/api/login
content-type:application/json

{
    "username": "user@example.com",
    "password": "mypass"
}

### Get all
GET http://localhost:8080/api/albums
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NjUzMDQ3MjMsInVzZXJuYW1lIjoidXNlckBleGFtcGxlLmNvbSJ9.LhfVBK-4BAtvdFYa6Ftdzw9pvJ4dapqr4h2MZVWI3iI


### Add one
POST http://localhost:8080/api/albums
content-type:application/json

{
    "id": "mynewalbum",
    "title": "a new album",
    "artist": "that great singer",
    "price": 123.45
}

### Get new one
GET http://localhost:8080/api/albums/mynewalbum
content-type:application/json

### Get non existing
GET http://localhost:8080/api/albums/non-existing
content-type:application/json
